drone_server_enable: "true"
drone_version: "latest"
drone_github_client_id: "e2bdde88b88f7ccf873a"
drone_github_client_secret: "b0412c975bbf2b6fcd9b3cf5f19c8165b1c14d0c"
drone_server_host: "368a7a66.ngrok.io"
drone_server_proto: "https"
drone_rpc_secret: "30075d074bfd9e74cfd0b84a5886b986"
# drone_database_driver: "postgres"
# drone_database_datasource: "postgres://drone:drone@postgres:5432/drone?sslmode=disable"
drone_database_driver: "mysql"
drone_database_datasource: "drone:drone@tcp(mysql:3306)/drone?parseTime=true"
docker_compose_version: "1.24.0"
docker_users:
  - multipass
