- hosts:
    - drone_server
    - drone_agent
  gather_facts: False
  tasks:
    - name: bootstrap
      raw: |
        test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
        test -e /usr/local/bin/pip || (curl  https://bootstrap.pypa.io/get-pip.py -o get-pip.py && python get-pip.py && pip install docker-py)
      changed_when: False
      become: true
      become_user: root
      register: out
    - debug: var=out.stdout_lines

- hosts:
    - drone_server
    - drone_agent
  roles:
    - base
    - docker
  become: true
  become_user: root

- hosts: drone_server
  roles:
    - drone
  become: true
  become_user: root
  vars:
    drone_server_enable: "true"
    drone_version: "latest"
    drone_github_client_id: "e2bdde88b88f7ccf873a"
    drone_github_client_secret: "b0412c975bbf2b6fcd9b3cf5f19c8165b1c14d0c"
    drone_server_host: "368a7a66.ngrok.io"
    drone_server_proto: "https"
    drone_rpc_secret: "30075d074bfd9e74cfd0b84a5886b986"
    drone_database_driver: "postgres"
    drone_database_datasource: "postgres://drone:drone@postgres:5432/drone?sslmode=disable"

- hosts: drone_agent
  roles:
    - drone
  become: true
  become_user: root
  vars:
    drone_agent_enable: "true"
    drone_version: "latest"
    drone_rpc_server: "http://192.168.64.2:8081"
    drone_rpc_secret: "30075d074bfd9e74cfd0b84a5886b986"
